[2022-07-22 08:45:46,535] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2022-07-22 08:45:46,556] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2022-07-22 08:45:46,558] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:46,559] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 08:45:46,559] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:46,590] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): start> on 2022-02-06 00:00:00+00:00
[2022-07-22 08:45:46,598] {standard_task_runner.py:52} INFO - Started process 217 to run task
[2022-07-22 08:45:46,603] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'start', 'scheduled__2022-02-06T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_4.py', '--cfg-path', '/tmp/tmpv3gmm637', '--error-file', '/tmp/tmpro5xim0k']
[2022-07-22 08:45:46,608] {standard_task_runner.py:80} INFO - Job 94: Subtask start
[2022-07-22 08:45:46,706] {task_command.py:371} INFO - Running <TaskInstance: dag1.start scheduled__2022-02-06T00:00:00+00:00 [running]> on host b51f0a1d5848
[2022-07-22 08:45:46,774] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=start
AIRFLOW_CTX_EXECUTION_DATE=2022-02-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-06T00:00:00+00:00
[2022-07-22 08:45:46,776] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_4.py", line 6, in add_task
    printf(f'args: x = {x}, y = {y}')
NameError: name 'printf' is not defined
[2022-07-22 08:45:46,785] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag1, task_id=start, execution_date=20220206T000000, start_date=20220722T084546, end_date=20220722T084546
[2022-07-22 08:45:46,798] {standard_task_runner.py:97} ERROR - Failed to execute job 94 for task start (name 'printf' is not defined; 217)
[2022-07-22 08:45:46,834] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 08:45:46,880] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
