[2022-07-22 08:45:24,049] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-01-03T00:00:00+00:00 [queued]>
[2022-07-22 08:45:24,059] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-01-03T00:00:00+00:00 [queued]>
[2022-07-22 08:45:24,060] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:24,061] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 08:45:24,061] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:24,074] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): start> on 2022-01-03 00:00:00+00:00
[2022-07-22 08:45:24,079] {standard_task_runner.py:52} INFO - Started process 139 to run task
[2022-07-22 08:45:24,082] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'start', 'scheduled__2022-01-03T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_4.py', '--cfg-path', '/tmp/tmpziamv52y', '--error-file', '/tmp/tmpyz1s46_w']
[2022-07-22 08:45:24,082] {standard_task_runner.py:80} INFO - Job 64: Subtask start
[2022-07-22 08:45:24,135] {task_command.py:371} INFO - Running <TaskInstance: dag1.start scheduled__2022-01-03T00:00:00+00:00 [running]> on host b51f0a1d5848
[2022-07-22 08:45:24,185] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=start
AIRFLOW_CTX_EXECUTION_DATE=2022-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-03T00:00:00+00:00
[2022-07-22 08:45:24,187] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_4.py", line 6, in add_task
    printf(f'args: x = {x}, y = {y}')
NameError: name 'printf' is not defined
[2022-07-22 08:45:24,198] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag1, task_id=start, execution_date=20220103T000000, start_date=20220722T084524, end_date=20220722T084524
[2022-07-22 08:45:24,207] {standard_task_runner.py:97} ERROR - Failed to execute job 64 for task start (name 'printf' is not defined; 139)
[2022-07-22 08:45:24,222] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 08:45:24,252] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
