[2022-07-22 08:45:41,863] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-01-27T00:00:00+00:00 [queued]>
[2022-07-22 08:45:41,876] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag1.start scheduled__2022-01-27T00:00:00+00:00 [queued]>
[2022-07-22 08:45:41,882] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:41,883] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-22 08:45:41,884] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 08:45:41,895] {taskinstance.py:1397} INFO - Executing <Task(_PythonDecoratedOperator): start> on 2022-01-27 00:00:00+00:00
[2022-07-22 08:45:41,903] {standard_task_runner.py:52} INFO - Started process 192 to run task
[2022-07-22 08:45:41,907] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag1', 'start', 'scheduled__2022-01-27T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_4.py', '--cfg-path', '/tmp/tmpeb2544pw', '--error-file', '/tmp/tmp2ldahuoh']
[2022-07-22 08:45:41,909] {standard_task_runner.py:80} INFO - Job 84: Subtask start
[2022-07-22 08:45:42,008] {task_command.py:371} INFO - Running <TaskInstance: dag1.start scheduled__2022-01-27T00:00:00+00:00 [running]> on host b51f0a1d5848
[2022-07-22 08:45:42,071] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag1
AIRFLOW_CTX_TASK_ID=start
AIRFLOW_CTX_EXECUTION_DATE=2022-01-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-27T00:00:00+00:00
[2022-07-22 08:45:42,076] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_4.py", line 6, in add_task
    printf(f'args: x = {x}, y = {y}')
NameError: name 'printf' is not defined
[2022-07-22 08:45:42,090] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag1, task_id=start, execution_date=20220127T000000, start_date=20220722T084541, end_date=20220722T084542
[2022-07-22 08:45:42,101] {standard_task_runner.py:97} ERROR - Failed to execute job 84 for task start (name 'printf' is not defined; 192)
[2022-07-22 08:45:42,120] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-22 08:45:42,190] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
